batchtools_sge(): help + tweak template script

diff --git a/inst/templates/slurm.tmpl b/inst/templates/slurm.tmpl
--- a/inst/templates/slurm.tmpl
+++ b/inst/templates/slurm.tmpl
@@ -7,9 +7,9 @@
 
 <% Slurm defaults
 defaults <- list(
-  nodes = 1,          # single-host processing
-   time = "00:05:00", # 5-min runtime
-   mem  = "100M"      # 100 MiB memory
+  nodes = 1,         # single-host processing
+  time = "00:05:00", # 5-min runtime
+  mem  = "100M"      # 100 MiB memory
 )
 resources <- c(resources, defaults[setdiff(names(defaults), names(resources))])
 opts <- unlist(resources, use.names = TRUE)
@@ -21,5 +21,24 @@ opts <- paste(opts, collapse = " ") %>
 #SBATCH --output=<%= log.file %>
 #SBATCH <%= opts %>
 
+echo "Batchtools job name: '<%= job.name %>'"
+
+echo "Session information:"
+date
+hostname
+which Rscript
+Rscript --version
+Rscript -e ".libPaths()"
+
 ## Launch R and evaluate the batchtools R job
+echo "Command: Rscript -e 'batchtools::doJobCollection("<%= uri %>")' ..."
 Rscript -e 'batchtools::doJobCollection("<%= uri %>")'
+res=$?
+echo " - exit code: ${res}"
+echo "Command: Rscript -e 'batchtools::doJobCollection("<%= uri %>")' ... done"
+
+## End-of-job summary
+sstat --format="JobID,AveCPU,MaxRSS,MaxPages,MaxDiskRead,MaxDiskWrite" --allsteps --jobs="${SLURM_JOB_ID}"
+
+## Relay the exit code from Rscript
+exit "${res}"
