Built-in templates: improve ERR trap to mention future.batchtools and prefix with ERROR:

diff --git a/inst/templates/torque.tmpl b/inst/templates/torque.tmpl
--- a/inst/templates/torque.tmpl
+++ b/inst/templates/torque.tmpl
@@ -35,7 +35,7 @@
 set -e          # exit on error
 set -u          # error on unset variables
 set -o pipefail # fail a pipeline if any command fails
-trap 'echo "Error on line $LINENO"; exit 1' ERR
+trap 'echo "ERROR: future.batchtools job script failed on line $LINENO" >&2; exit 1' ERR
 
 echo "Batchtools information:"
 echo "- job name: '<%= job.name %>'"
